name: jupyter-multilang
channels:
  - conda-forge
dependencies:
  - python=3.10
  - notebook
  - jupyterlab
  - ipywidgets
  - xeus-cling      # Noyau C++ (C++11, 14, 17)
  - openjdk=17      # Version complète de Java pour le compilateur
  - ijava           # NOYAU JAVA INTERACTIF POUR JUPYTER
