name: jupyter-multilang
channels:
  - conda-forge
dependencies:
  - python=3.10
  - notebook
  - jupyterlab
  - ipywidgets
  - xeus-cling      # Installe instantanément le Noyau C++
  - maven           # Nécessaire pour finaliser l'installation du Noyau Java
