#!/bin/bash
# 1. Télécharger et installer le noyau Java officiel
curl -L https://github.com -o /tmp/ijava.zip
unzip /tmp/ijava.zip -d /tmp/ijava_pack
python /tmp/ijava_pack/install.py --sys-prefix
rm -rf /tmp/ijava.zip /tmp/ijava_pack
