#!/bin/bash

# 1. Télécharger la dernière version stable du noyau IJava (Java 9+)
curl -L https://github.com -o ijava.zip

# 2. Décompresser le fichier
unzip ijava.zip -d ijava_pack

# 3. Installer le noyau Java pour l'utilisateur Jupyter (jovyan)
python ijava_pack/install.py --sys-prefix

# 4. Nettoyer les fichiers temporaires pour alléger le conteneur
rm -rf ijava.zip ijava_pack
